apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: phpadmin-pod
  name: phpadmin-pod
spec:
  containers:
  - image: phpmyadmin:latest
    name: phpadmin-pod
    envFrom:
    - configMapRef:
        name: phpadmin-cm
    - secretRef:
        name: phpadmin-secret
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: phpadmin-pod
  name: phpadmin-svc
spec:
  ports:
  - port: 8085
    protocol: TCP
    targetPort: 80
  selector:
    run: phpadmin-pod
  type: NodePort
status:
  loadBalancer: {}