apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: phpapp-pod
  name: phpapp-pod
spec:
  containers:
  - image: fir3eye/php-app:v8
    name: phpapp-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: phpadmin-pod
  name: phpapp-svc
spec:
  ports:
  - port: 8086
    protocol: TCP
    targetPort: 80
  selector:
    run: phpadmin-pod
  type: NodePort
status:
  loadBalancer: {}